name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  simple_deployment_pipline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - name: yarn install
        run: yarn
      - name: lint code
        run: yarn eslint
      - name: build
        run: yarn build
      - name: test
        run: yarn test
